### ISSUE TITLE
Can we customize the outputs format of Model?

### ISSUE THREAD

**Issue by yu-iskw** [SeldonIO/seldon-core#565] opened 2019-05-15 19:03 UTC
# Motivation
When we want to return multiple values with `Model`, we can format the outputs and label them with `class_names`. The order of returned values should be kept. Consider if we want to modify the returned value. The order of existing names should be remained. 

Otherwise, I would like to know a better way to return multiple values. `tags` method can look good. But, I am not sure.

I would like to customize the outputs format, since the current spec of outputs format is not useful from the requesters' point of view. Is there any way to customize that?

## Current spec
```
{
  "data": {
    "names": [
      "class",
      "probability"
    ],
    "ndarray": [
      [
        3,
        0.567219348236373
      ]
    ]
  },
  "meta": {
    "tags": {
      "version": "1.0.0"
    }
  }
}
```

## Format I want
I would like to format the output as below. Expressing the returned values as a map would be much better flexible, even when we put additional values to the returned values. I understand the duplicated labels that are `class` and `probability` in the below case can increase the data size of returned value. In my opinion, it doesn't matter, since we usually request to the API with a data point. The duplication is not significant.
```
{
  "predictions": [
    {"class": 3, "probability": 0.567219348236373}
  ],
  "meta": {
    "tags": {
      "version": "1.0.0"
    }
  }
}
```

**Comment by cliveseldon** [comment] 2019-05-16 06:53
I think this would come under the area of allowing arbitrary JSON in the input and output for which there is an existing issues: #434 which is slated for the next release.

**Comment by yu-iskw** [comment] 2019-05-16 19:01
That is what I want to do. The formats of inputs and outputs can get more user-friendly. The current formats seems sklearn-friendly.

**Comment by cliveseldon** [comment] 2019-05-16 19:33
We plan to provide arbitrary JSON input and output in a field, e.g. `jsonData`. Would this fit your use case?
See #434

**Comment by yu-iskw** [comment] 2019-05-16 19:38
I think so, as long as we can use a flexible format with arbitrary JSON. I don't stock to have a fixed format. Customizable input and output are more convenient.

**Comment by yu-iskw** [comment] 2019-05-16 19:39
I want to know more detail about the specification of #434 . And I would be glad to join the discussion. Please keep me in the loop.

**Comment by cliveseldon** [comment] 2019-05-28 12:32
Close as duplicate of #434

**Closed by cliveseldon** 2019-05-28 12:32 UTC
