### ISSUE TITLE
Seldon container engine fails to start

### ISSUE THREAD

**Issue by RyanZgmzpn** [SeldonIO/seldon-core#4380] opened 2022-10-13 11:11 UTC
seldon-core-operator:1.7.0-dev
seldon-core-executor:1.9.1

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: distri-image1
  namespace: seldon
spec:
  annotations:
    seldon.io/engine-seldon-log-messages-externally: "true"
    seldon.io/grpc-timeout: "100000"
    seldon.io/rest-timeout: "100000"
  name: distri-image1
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - env:
          - name: GUNICORN_WORKERS
            value: "1"
          - name: GUNICORN_THREADS
            value: "10"
          - name: SELDON_LOG_LEVEL
            value: INFO
          image: seldonio/metadata-generic-node:1.14.0-dev
          imagePullPolicy: Always
          name: b
          resources:
            limits:
              cpu: "8"
              memory: 8Gi
            requests:
              cpu: 100m
              memory: 512m
          securityContext:
            runAsUser: 0
    - spec:
        containers:
        - env:
          - name: GUNICORN_WORKERS
            value: "1"
          - name: GUNICORN_THREADS
            value: "10"
          - name: SELDON_LOG_LEVEL
            value: INFO
          image: seldonio/metadata-generic-node:1.14.0-dev
          imagePullPolicy: Always
          name: c
          resources:
            limits:
              cpu: "8"
              memory: 8Gi
            requests:
              cpu: 100m
              memory: 512m
          securityContext:
            runAsUser: 0

        - env:
          - name: GUNICORN_WORKERS
            value: "1"
          - name: GUNICORN_THREADS
            value: "10"
          - name: SELDON_LOG_LEVEL
            value: INFO
          image: seldonio/metadata-generic-node:1.14.0-dev
          imagePullPolicy: Always
          name: a
          resources:
            limits:
              cpu: "8"
              memory: 8Gi
            requests:
              cpu: 100m
              memory: 512m
          securityContext:
            runAsUser: 0

    engineResources: {}
    graph:
      children:
      - endpoint:
          type: REST
        logger:
          mode: all
        name: b
        type: MODEL
      - endpoint:
          type: REST
        logger:
          mode: all
        name: c
        type: MODEL
      endpoint:
        type: REST
      logger:
        mode: all
      name: a
      type: COMBINER
    name: default
    replicas: 1
    svcOrchSpec: {}
    traffic: 100
  protocol: seldon
```

Hi, Team:

Above is the sdep yaml file we use to create an seldon deployment, but the seldon container engine failed to start.

Could you help to check whether inference graph on several pods like this is supported?

**Comment by cliveseldon** [comment] 2022-10-14 06:18
Can you try with latest seldon core 1.14.0-dev?

**Comment by yaliqin** [comment] 2022-10-26 19:59
I updated seldon-core-operator and seldon-core-executor image to 1.15.0-dev.  But the problem is still there.

**Comment by cliveseldon** [comment] 2022-10-27 16:09
I have tried with 1.15-dev and all is ok. Can you clarify the error you are seeing with the logs from the executor container and also check that all images controller and executor are 1.15.0-dev?

**Comment by yaliqin** [comment] 2022-10-27 17:54
Hi @cliveseldon ,   sorry I verified again and found the deployment succeeded. I found sometimes it needs longer time for seldon-container-engine ready. Please close the issue.

**Comment by cliveseldon** [comment] 2022-10-28 06:18
Glad it works!

**Closed by cliveseldon** 2022-10-28 06:18 UTC
Labels: bug
