### ISSUE TITLE
AttributeError: Can't pickle local object 'main.<locals>.grpc_prediction_server' in Linux

### ISSUE THREAD

**Issue by 0xHigos** [SeldonIO/seldon-core#4388] opened 2022-10-20 05:18 UTC
I am using pytorch*2+tfl*1 models,  it required me to using CUDA, so I have to set multiple thread method "spawn", but I got an Error said: "AttributeError: Can't pickle local object 'main.<locals>.grpc_prediction_server'"

my env : 
+ Python 3.8.10
+ seldon-core 1.14.1

there is the demo code for reproduce this problem:
```
import multiprocessing
multiprocessing.set_start_method("spawn")
from multiprocessing import Pool, cpu_count


class MyModel:
    def __init__(self):
        pass

    def predict(*args, **kwargs):
        return ["hello", "world"]
````

there is the cmd I used:
` seldon-core-microservice MyModel --service-type MODEL --persistence 0
`

How can we re solve the problem when we must use "spawn" style to start my multiple thread

**Comment by 0xHigos** [comment] 2022-10-20 05:19
I tried this solution, but it seems not work.
`import pathos
from pathos.multiprocessing import ProcessingPool as Pool, cpu_count
import multiprocess.context as ctx
ctx._force_start_method('spawn')`

**Comment by RafalSkolasinski** [comment] 2022-11-28 22:08
Hi @0xHigos, thanks for the report.

Could you also attach minimal example that could reproduce the original problem using some minimal (or publicly available) pytorch model? We will then be able to look at it together with https://github.com/SeldonIO/seldon-core/issues/4429 once we get a chance and address the issue at the core.

**Comment by rlleshi** [comment] 2022-11-29 12:29
You can actually reproduce the problem using the example that I provided in #4429. Just add `mp.set_start_method('spawn')` to the seldon wrapper.

**Comment by RafalSkolasinski** [comment] 2022-11-29 19:35
Well, if `mp.set_start_method('spawn')` causes error that grpc server is not pickle-able then there will not be an easy way around it.

**Comment by rlleshi** [comment] 2022-11-30 13:43
I think the error is mostly due to the way how multiprocessing is handled within the microservice (e.g. [see](https://stackoverflow.com/questions/72766345/attributeerror-cant-pickle-local-object-in-multiprocessing)). The error persists even if I specify `--grpc-workers 0` since there another metrics' server is starting.

**Comment by nadworny** [comment] 2023-03-27 09:38
has anybody found a solution for that? In my case the same model starts fine as docker container within k8s but when I want to start it locally with seldon-core-microservice, I get the same error as the author. I need to debug some things with that model and since we're using s2i to build the image (and it takes very long time to build as it doesn't seem to be re-using docker layers), it's very difficult and time consuming.
Any further idea how can I easily build and start such a container locally?

**Comment by cliveseldon** [comment] 2023-06-20 10:08
Fixed in MLServer

**Closed by cliveseldon** 2023-06-20 10:08 UTC
Labels: bug, v1
