### ISSUE TITLE
seldon-core-operator CRD's incompatible with K8s v1.18

### ISSUE THREAD

**Issue by iamlittle** [SeldonIO/seldon-core#1675] opened 2020-04-08 19:41 UTC
Installing the seldon-core-operator on a fresh v1.18 Kubernetes install throws an error:

```
Error: CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[containerSpec].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
```

I believe this is due to an [API change in v1.18](https://kubernetes.io/docs/setup/release/notes/).

> CustomResourceDefinition schemas that use x-kubernetes-list-map-keys to specify properties that uniquely identify list items must make those properties required or have a default value, to ensure those properties are present for all list items. See https://kubernetes.io/docs/reference/using-api/api-concepts/&#35;merge-strategy for details. (#88076, @eloyekunle) [SIG API Machinery and Testing]

I was able to work around by installing a crd definition exported from a successful v1.17 install and installing seldon-core-operator with `crd.create=false`.

Steps to reproduce:
```
curl https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz -o helm-v3.1.2-linux-amd64.tar.gz
tar -xzvf helm-v3.1.2-linux-amd64.tar.gz
chmod a+x linux-amd64/helm
mv linux-amd64/helm /usr/local/bin/

helm repo add ambassador https://www.getambassador.io
helm repo add seldon https://storage.googleapis.com/seldon-charts

helm upgrade ambassador ambassador/ambassador --install
helm upgrade seldon-core seldon/seldon-core-operator --install --version=1.0.3-SNAPSHOT --set ambassador.enabled=true --set crd.create=true
```

**Comment by cliveseldon** [comment] 2020-04-08 21:35
Thanks for these details. We will need to see what we need to add to the Kustomize definitions.

**Comment by DenisOgr** [comment] 2020-04-29 13:10
Same problem! Downgrade Kubernetes to 1.17.0 and it fixes.

**Comment by xaniasd** [comment] 2020-05-07 10:01
FYI this affects local development as well, because kind images are not pinned to a specific version

**Comment by vega42** [comment] 2020-05-29 01:39
I can confirm. After downgrading my minikube using:

minikube start --kubernetes-version v1.17.0
 
I can get past the issue in the seldon-core setup.

**Comment by Atharex** [comment] 2020-05-29 08:26
The same error came up with the prometheus operator. 
https://github.com/coreos/prometheus-operator/issues/3122

I can confirm that when I adapted the schema to make the property required, it fixed the problem and the install works again on 1.18+ (though not sure if that is a proper "fix" for your operator)

In the prometheus operator they fixed the problem by upgrading their CRD API to v1 for kubernetes >= 1.18  and keeping also the v1beta1 API for kubernetes < 1.16

**Comment by cliveseldon** [comment] 2020-05-29 08:39
Thanks for the info we will be looking to solve this post 1.2.0 release for 1.3.0 release

**Comment by shawnzhu** [comment] 2020-06-20 21:58
I hit this problem when installing kubeflow (w/ `seldon-core-operator:1.1.0`) on k8s v1.18. is this caused by https://github.com/kubernetes/kubernetes/issues/91395 ?

**Comment by cliveseldon** [comment] 2020-06-21 07:41
Yes that is the core reason. We need to upgrade to v1 CRDs but need at same time to keep backwards compataibility for older k8s. So I think we will need options to create both.

**Comment by cliveseldon** [comment] 2020-06-25 07:56
Duplicate of #1678

**Closed** 2020-08-30 09:10 UTC
Labels: area/k8s, bug, priority/p1

**Comment by shadowmodder** [comment] 2020-09-03 05:59
+1 need this backward compatible

**Comment by cliveseldon** [comment] 2020-09-03 07:13
It should be. The helm chart checks for k8s version and deploys a v1beta1 CRD for k8s <1.18 and a v1 CRD for >- 1.18.
There is #2367 which we need to investigate before release.

**Comment by arunbenoyv** [comment] 2020-09-22 17:10
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Helm install is resulting in the same error

helm install seldon-core seldon-core-operator  --repo https://storage.googleapis.com/seldon-charts  --set usageMetrics.enabled=true --set ambassador.enabled=true
Error: CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[containerSpec].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]

**Comment by cliveseldon** [comment] 2020-09-22 18:10
The fix is in master and will be in next release @arunbenoyv

**Comment by salinaaaaaa** [comment] 2022-02-17 15:53
Separate but related ques here: When we set the ```--set crd.create=true`` to true, what does that CRD do and what is it for? I could not find anything in the docs that explains this.

**Comment by cliveseldon** [comment] 2022-02-17 16:00
This is used for cases where we want the operator to create the CRD - its usually used just in Marketplaces where we can't install the CRD separately first

**Comment by salinaaaaaa** [comment] 2022-02-17 16:02
So on a vanilla kubernetes install, it can be set to false and model
serving with mlflow and metrics in grafana will work?

**Comment by cliveseldon** [comment] 2022-02-17 17:35
Worth following [our install methods](https://docs.seldon.io/projects/seldon-core/en/latest/nav/installation.html) to see if they fit your use. With Helm the chart will install the CRD.
