### ISSUE TITLE
Ensure only changing weight of predictor doesn't cause new rollout

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1078] opened 2019-11-08 15:42 UTC
default -> canary -> default should not cause default to be recreated

 default -> adding explainer should not cause default to be recreated

Checks to stop reapply of semantic not changed components

**Comment by ryandawsonuk** [comment] 2020-01-16 13:11
Duplicate of https://github.com/SeldonIO/seldon-core/issues/1110

**Closed** 2020-01-31 11:19 UTC
