### ISSUE TITLE
gitops demo

### ISSUE THREAD

**Issue by errordeveloper** [SeldonIO/seldon-core#67] opened 2018-01-24 13:01 UTC
https://github.com/errordeveloper/seldon-gitops

The setups steps haven't been documented in the repo yet, happy to walk through it.

One thing to note is that I've done some more work extending what I have already contributed via #51. Namely, I added GCB config and optimised the build to use cache properly.

**Comment by cliveseldon** [comment] 2018-11-08 16:41
Duplicate of #11

**Closed by cliveseldon** 2018-11-08 16:41 UTC
