### ISSUE TITLE
seldon-batch-processor to support https and sslverify 

### ISSUE THREAD

**Issue by omerfsen** [SeldonIO/seldon-core#2638] opened 2020-11-13 19:17 UTC
Currently seldon-batch-processor does not support https protocol as parameters so it supports ` -h, --host TEXT `  but this is only hostname not protocol so request these two arguments to be supported:

```bash
--protocol http/https
--sslverify true/false 
```
so we have
```bash
        seldon-batch-processor \
            --deployment-name "sklearn" \
            --benchmark \
            --namespace "emtech" \
            --host "istio-ingressgateway.istio-system.svc.cluster.local" \
            --protocol https \
            --sslverify false \
            --workers "9" \
            --data-type "data" \
            --payload-type "ndarray" \
            --retries "3" \
            --input-data-path "/assets/input-data.txt" \
            --output-data-path "/assets/output-data.txt"
```

We are disabling http endpoint on istio gateway for security purposes and using internal CA so sslverify can be good alternative. Also not sure if --host supports port number so instead of 
```bash
            --host "istio-ingressgateway.istio-system.svc.cluster.local" \
```

we may use 

```bash
            --host "istio-ingressgateway.istio-system.svc.cluster.local:8080" \
```

**Comment by cliveseldon** [comment] 2020-11-26 10:37
closing as duplicate of #2702

**Closed by cliveseldon** 2020-11-26 10:37 UTC
Labels: triage
