### ISSUE TITLE
Scheduler container not starting in local installation

### ISSUE THREAD

**Issue by habilmohammed** [SeldonIO/seldon-core#4545] opened 2023-01-04 05:08 UTC
Hi,

I am trying to setup Seldon V2 on a VM using the docker compose by following the steps( https://docs.seldon.io/projects/seldon-core/en/v2/contents/getting-started/docker-installation/index.html ) . When I run make deploy-local , All the images got downloaded and started the containers except for scv2-scheduler-1 which is in Created state but not starting up with no logs, eventually giving me an error like this

Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: chdir to cwd ("/home/nonroot") set in config.json failed: permission denied: unknown
makeÆ1Å: *** ÆMakefile:292: start-allÅ Error 1
makeÆ1Å: Leaving directory '/home/a263257/seldon-repo/seldon-core/scheduler'
make: *** ÆMakefile:5: deploy-localÅ Error 2

Any suggestions are greatly appreciated. 

Thanks.

Docker version 20.10.5+dfsg1, build 55c4c88
Docker Compose version v2.6.1
Go version go1.19.4 linux/amd64
Make version GNU Make 4.3

<img width="1503" alt="Screenshot 2023-01-04 at 10 33 44 AM" src="https://user-images.githubusercontent.com/31307307/210488205-3b1bdf0b-f2f1-4796-9d61-4c99dddc6c47.png">
<img width="1497" alt="Screenshot 2023-01-04 at 10 22 20 AM" src="https://user-images.githubusercontent.com/31307307/210488211-0f2282fe-6ce5-4e67-bbbb-daabae87dac0.png">
<img width="1493" alt="Screenshot 2023-01-04 at 10 21 50 AM" src="https://user-images.githubusercontent.com/31307307/210488214-05480e29-a667-4164-913f-a0fc67ff580d.png">
<img width="1374" alt="Screenshot 2023-01-04 at 2 22 57 PM" src="https://user-images.githubusercontent.com/31307307/210518418-26f6d316-6302-4e62-a87a-e570844d2bec.png">

**Comment by sakoush** [comment] 2023-01-04 09:53
@habilmohammed we suspect that there might be a mismatch of user/priviliges on your setup. Could you please runt the following and share the output to be able to confirm? 
- `echo $UID`
- `ls -la /home/a263257/seldon-repo/seldon-core/scheduler`

**Comment by habilmohammed** [comment] 2023-01-04 10:18
@sakoush Thanks for the quick response. Please find the output of the commands attached.

<img width="721" alt="Screenshot 2023-01-04 at 3 46 14 PM" src="https://user-images.githubusercontent.com/31307307/210533737-3fd8ffd2-403b-4b61-aeb6-f41e2a4a452c.png">

**Comment by RafalSkolasinski** [comment] 2023-01-04 10:22
User inside the docker images has UID `1000`. The conflict of user IDs is what most likely causes the issue. You will most likely need to modify docker compose manifests to account for this change

**Comment by RafalSkolasinski** [comment] 2023-01-04 10:25
Possibly force to run containers as user 1010 by setting
```yaml
services:
  scheduler:
    user: 1010
```
or similar in `all-internal.yaml`

**Comment by sakoush** [comment] 2023-01-04 10:30
it is likely also that you need the same change for `triton` and `mlserver` services as well at some point.

**Comment by habilmohammed** [comment] 2023-01-05 09:47
I tried updating the all-internal.yaml file to run containers as user 1010 but it doesn't seem to work, getting the same error response. I am trying out other ways to check if we can force the user to 1010. 

Attaching the all-internal changes I have made.
<img width="755" alt="Screenshot 2023-01-05 at 3 13 33 PM" src="https://user-images.githubusercontent.com/31307307/210750475-b20e117a-c977-49a5-89c3-1c9356a87b0b.png">

**Comment by sakoush** [comment] 2023-01-05 10:04
you might need to change also the group id. check [here](https://github.com/SeldonIO/seldon-core/blob/520986128f2d011ee150db9002dc2116ddfa455f/scheduler/all-base.yaml#L167). You can get the group id with `id -g`

I suggest  that you do the user/groupd changes in `all-base.yaml` as it is where they are currently defined and I am not sure about the override semantics of compose.

**Comment by sakoush** [comment] 2023-01-16 15:24
@habilmohammed it seems that you also need to upgrade docker-compose to a recent version. We got your issue working on version 1.15.1.

**Comment by habilmohammed** [comment] 2023-01-30 08:53
@sakoush Regret the delayed response.

I have updated the all-base.yml as well as all-internal.yml to add the user:group for scheduler, mlserver and triton. 
Also updated the docker compose version to 2.15.1 . Seems like this issue is still present :(

We are trying it out on a VM instance inside GCP, attaching the error logs below. Would you suggest to go via k8s cluster installation if docker compose is giving us issues.

Thanks.

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/31307307/215430603-ee1761da-80a1-4b40-82df-4e24d118aeec.png">
<img width="850" alt="image" src="https://user-images.githubusercontent.com/31307307/215430629-5750c6fc-9737-4836-a212-aa82669b78be.png">

**Comment by cliveseldon** [comment] 2023-01-30 09:03
Local docker compose use will greatly help your development process. Any ideas @sakoush - looks like Docker compose volumes are located at a place the user does not have permission.

**Comment by sakoush** [comment] 2023-01-30 20:39
@habilmohammed your latest error is slightly different from the error you shared initially so the cause could be different. In our runs we didnt need to add the user id / group setting for triton / mlserver. Given that mlserver failed to start in your latest run, could you remove the `user` setting from `mlserver` service and try again?

Also could you provide the docker version as well?

**Comment by cliveseldon** [comment] 2023-03-18 18:54
Closing this. Please update us if still not working with latest.

**Closed by cliveseldon** 2023-03-18 18:54 UTC
Labels: v2
