### ISSUE TITLE
seldon-core-microservice: error: unrecognized arguments: REST

### ISSUE THREAD

**Issue by FarshadMovahed-REISys** [SeldonIO/seldon-core#2951] opened 2021-02-12 01:13 UTC
## Describe the bug

I followed this [post](https://towardsdatascience.com/a-simple-mlops-pipeline-on-your-local-machine-db9326addf31) and I built a Docker image using the Dockerfile (see the Appendix) and executed a python code using the image to the get predictions from a machine learning model. But, I got the following error. All the files can be found [here](https://github.com/kylegallatin/mlops-pipeline). How can I provide "REST" as an API type argument with the seldon-core-microservice command in Dockerfile? 

seldon-core-microservice: error: unrecognized arguments: [REST]

Appendix: 
**** Dockerfile ****

`
FROM python:3.7-slim

COPY . /app
WORKDIR /app
#RUN pip install -r requirements.txt
RUN pip install sklearn seldon-core
EXPOSE 5000

ENV MODEL_NAME Model
ENV API_TYPE REST
ENV SERVICE_TYPE MODEL
ENV PERSISTENCE 0

CMD exec seldon-core-microservice ${MODEL_NAME} ${API_TYPE} --service-type ${SERVICE_TYPE} --persistence $PERSISTENCE
`

## To reproduce

docker build -t seldon-app .
docker run -p 5001:5000 -it seldon-app

## Environment

I ran the scripts locally on macOS Catalina 

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment] 2021-02-18 08:19
Duplicate of #2896

**Closed by cliveseldon** 2021-02-18 08:19 UTC
Labels: bug, triage
