### ISSUE TITLE
Can't create resources under v1.18

### ISSUE THREAD

**Issue by Ogaday** [SeldonIO/seldon-core#1678] opened 2020-04-09 17:05 UTC
On a fresh MicroK8s cluster I can't create Seldon resources. On v1.17, for comparison, everything works as expected as far as I can see.

```bash
sudo snap install microk8s --classic --channel=1.18/stable
# Download snap "microk8s" ...
# microk8s (1.18/stable) v1.18.0 from Canonical✓ installed
microk8s.kubectl version
# Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
# Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
snap list helm
# Name  Version  Rev  Tracking       Publisher     Notes
# helm  3.1.2    200  latest/stable  snapcrafters  classic
microk8s.enable dns istio registry storage
# Enabling DNS ...
helm version
# version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
microk8s.istioctl version
# client version: 1.3.4
# control plane version: 1.3.4
kubectl create namespace seldon-system
# namespace/seldon-system created
helm install seldon-core seldon-core-operator\
    --repo https://storage.googleapis.com/seldon-charts\
    --set usageMetrics.enabled=true\
    --namespace seldon-system\
    --set istio.enabled=true
# NAME: seldon-core
# LAST DEPLOYED: Thu Apr  9 17:28:15 2020
# NAMESPACE: seldon-system
# STATUS: deployed
# REVISION: 1
# TEST SUITE: None
kubectl get all -n seldon-system
# NAME                                             READY   STATUS    RESTARTS   AGE
# pod/seldon-controller-manager-5c94779c7d-vvlpb   1/1     Running   0          4m41s
# 
# NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
# service/seldon-webhook-service   ClusterIP   10.152.183.216   <none>        443/TCP   4m41s
# 
# NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
# deployment.apps/seldon-controller-manager   1/1     1            1           4m41s
# 
# NAME                                                   DESIRED   CURRENT   READY   AGE
# replicaset.apps/seldon-controller-manager-5c94779c7d   1         1         1       4m41s
helm install single-model helm-charts/seldon-single-model
# Error: SeldonDeployment.machinelearning.seldon.io "single-model" is invalid: metadata.managedFields.fieldsType: Invalid value: "": must be `FieldsV1`
kubectl apply -f - << END
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: iris-model
spec:
  name: iris
  predictors:
  - graph:
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/iris
      name: classifier
    name: default
    replicas: 1
END
# The SeldonDeployment "iris-model" is invalid: metadata.managedFields.fieldsType: Invalid value: "": must be `FieldsV1`
```

Fresh install of v1.17:

```bash
microk8s.stop
# Stopped.
sudo snap remove --purge microk8s
# microk8s removed
sudo snap install microk8s --classic --channel=1.17/stable
# Download snap "microk8s" ...
# microk8s (1.17/stable) v1.17.4 from Canonical✓ installed
microk8s.kubectl version
# Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
# Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
kubectl create namespace seldon-system
# namespace/seldon-system created
helm install seldon-core seldon-core-operator\
    --repo https://storage.googleapis.com/seldon-charts\
    --set usageMetrics.enabled=true\
    --namespace seldon-system\
    --set istio.enabled=true
# NAME: seldon-core
# LAST DEPLOYED: Thu Apr  9 17:48:00 2020
# NAMESPACE: seldon-system
# STATUS: deployed
# REVISION: 1
# TEST SUITE: None
kubectl get all -n seldon-system
# NAME                                            READY   STATUS    RESTARTS   AGE
# pod/seldon-controller-manager-c8d5f9448-67ltg   1/1     Running   0          3m27s
# 
# NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
# service/seldon-webhook-service   ClusterIP   10.152.183.205   <none>        443/TCP   3m27s
# 
# NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
# deployment.apps/seldon-controller-manager   1/1     1            1           3m27s
# 
# NAME                                                  DESIRED   CURRENT   READY   AGE
# replicaset.apps/seldon-controller-manager-c8d5f9448   1         1         1       3m27s
helm install single-model helm-charts/seldon-single-model
# NAME: single-model
# LAST DEPLOYED: Thu Apr  9 17:52:23 2020
# NAMESPACE: default
# STATUS: deployed
# REVISION: 1
# TEST SUITE: None
kubectl apply -f - << END
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: iris-model
spec:
  name: iris
  predictors:
  - graph:
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/iris
      name: classifier
    name: default
    replicas: 1
END
# seldondeployment.machinelearning.seldon.io/iris-model created
kubectl get all
# NAME                                                READY   STATUS    RESTARTS   AGE
# pod/iris-default-4903e3c-794fcfff5-shzjh            0/2     Running   0          5m34s
# pod/single-model-default-de240ba-588969bfd6-psn6m   2/2     Running   0          6m24s
# 
# NAME                                                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
# service/iris-default-classifier-seldonio-sklearnserver-rest-0-2   ClusterIP   10.152.183.143   <none>        9000/TCP            5m34s
# service/kubernetes                                                ClusterIP   10.152.183.1     <none>        443/TCP             16m
# service/seldon-903f456dbf43f52893de88f49d3f8964                   ClusterIP   10.152.183.122   <none>        9000/TCP            6m24s
# service/single-model-single-model-default                         ClusterIP   10.152.183.62    <none>        8000/TCP,5001/TCP   2m20s
# 
# NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
# deployment.apps/iris-default-4903e3c           0/1     1            0           5m34s
# deployment.apps/single-model-default-de240ba   1/1     1            1           6m24s
# 
# NAME                                                      DESIRED   CURRENT   READY   AGE
# replicaset.apps/iris-default-4903e3c-794fcfff5            1         1         0       5m34s
# replicaset.apps/single-model-default-de240ba-588969bfd6   1         1         1       6m24s
```

**Comment by cliveseldon** [comment] 2020-04-27 07:30
Reference: https://github.com/kubedb/issues/issues/739

**Comment by cliveseldon** [comment] 2020-06-25 07:59
Duplicate of #1675

**Closed** 2020-06-25 07:59 UTC
Labels: priority/p1
