### ISSUE TITLE
v2: helm install failure

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#4541] opened 2023-01-03 09:05 UTC
Taken from [slack conversation](https://seldondev.slack.com/archives/C03DQFTFXMX/p1672700896756229) fro @amoldavsky 

error seen:

```
❯ helm install seldon-core-v2 seldon-core-v2-setup -n seldon-core-v2
Error: parse error at (seldon-core-v2-setup/templates/seldon-v2-components.yaml:563): unclosed action
```

**Comment by cliveseldon** [comment] 2023-01-03 09:08
Tried to replicate but worked with:

Setup [Kind](https://docs.seldon.io/projects/seldon-core/en/v2/contents/getting-started/kubernetes-installation/ansible.html#create-kind-cluster) and [Ecosystem](https://docs.seldon.io/projects/seldon-core/en/v2/contents/getting-started/kubernetes-installation/ansible.html#create-kind-cluster) with Ansible scripts

```
git clone --depth 1 --branch v2.0.0 git@github.com:SeldonIO/seldon-core.git scv2-v2.0.0
cd scv2-v2.0.0
helm install seldon-core-v2-crds  k8s/helm-charts/seldon-core-v2-crds
helm install seldon-core-v2  k8s/helm-charts/seldon-core-v2-setup --namespace seldon-mesh
```

```
helm version
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}

```

**Comment by amoldavsky** [comment] 2023-01-03 11:56
```
❯ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

**Comment by amoldavsky** [comment] 2023-01-03 12:05
On my end due to how our cicd projects are setup I have to submodule the seldon-core repo and symlink to each helm chart under another directory in the project. This does not change the essence of the submodule and the error, since it is complaining about a multi line string (within quotes).

steps:
```
git submodule add https://github.com/SeldonIO/seldon-core.git src                                          ✔  06:53:30 
cd src
git checkout tags/v2.0.0 
cd ..
git submodule update --remote
cd deploy/helm
ln -s ../../src/k8s/helm-charts/seldon-core-v2-crds seldon-core-v2-crds
ln -s ../../src/k8s/helm-charts/seldon-core-v2-setup seldon-core-v2-setup
```

Now with symlinks:
```
❯ helm install seldon-core-v2 seldon-core-v2-setup -n seldon-core-v2
Error: parse error at (seldon-core-v2-setup/templates/seldon-v2-components.yaml:723): unclosed action
```

**Comment by RafalSkolasinski** [comment] 2023-01-03 12:21
From Slack discussion, @amoldavsky managed to resolve by upgrading helm to 
```
❯ helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}
```

The issue is related to the fact that we generated v2 helm charts using kustomize and kustomize is breaking longer lines. Upstream ticket: https://github.com/kubernetes-sigs/kustomize/issues/947

Closing for now as charts work properly with latest helm.

**Closed by RafalSkolasinski** 2023-01-03 12:21 UTC
Labels: bug, v2
