### ISSUE TITLE
Enable skip-certificate-verify on batch processor component

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2702] opened 2020-11-24 11:40 UTC
Currently the batch processor component cannot work with self signed certificates. The underlying SeldonClient can be exposed through the client to allow unsecure / skip-ssl-verify to ensure it doesn't require the checks. For GRPC this woudl also be required to skip SSL check.

**Comment by omerfsen** [comment] 2020-11-26 10:48
Also afaik batch processor does not support https istio ingress so

1. Able to define schema (http/https)
2. Skip ssl verify
3. Define different port number (as ingress gateway may run on different ports)

It is as defined #2638 which is just closed of being duplicate of this issue

**Comment by cliveseldon** [comment] 2022-01-09 14:29
Close for larger refactor of Batch processor.

**Closed by cliveseldon** 2022-01-09 14:29 UTC
Labels: priority/p2
