### ISSUE TITLE
Deploying custom MLflow model - stuck at "Readiness probe failed"

### ISSUE THREAD

**Issue by FilipVel** [SeldonIO/seldon-core#3186] opened 2021-05-12 12:25 UTC
Hey, so I have problem deploying a custom MLflow model made with the 'mlflow.pyfunc.model'

The model that I have is as follows:
```
class CarModel(mlflow.pyfunc.PythonModel):
    def __init__(self,model,std_scaler,pw_trans,imputer,encoders,preprocess_data):
        self.model = model
        self.std_scaler = std_scaler
        self.pw_trans = pw_trans
        self.imputer = imputer
        self.encoders = encoders
        self.preprocess_data = preprocess_data
    def predict(self, context, model_input):
        processed = self.preprocess_data(df = model_input,
                                        std_scaler = self.std_scaler,
                                        pw_trans = self.pw_trans,
                                        imputer = self.imputer,
                                        encoders = self.encoders)
        return self.model.predict(processed)
```
Apart from the model I have the MLmodel file with the following content:
```
flavors:
  python_function:
    cloudpickle_version: 1.5.0
    env: conda.yaml
    loader_module: mlflow.pyfunc.model
    python_model: python_model.pkl
    python_version: 3.8.3
utc_time_created: '2021-05-12 09:08:02.201931'
```
and conda.yaml
```
channels:
- defaults
- conda-forge
dependencies:
- python=3.8.3
- pip
- pip:
  - mlflow
  - xgboost==1.3.3
  - cloudpickle==1.5.0
  - scikit-learn==0.24.1
name: mlflow-env
```

When I try to run the model locally it with `mlflow models serve -m model_name` it works just fine.

Next I uploaded the model with the conda.yaml and MLmodel files to a Google cloud bucket that I wanted to use as a source to build a seldon core deployment.
I tried deploying the model with the following code:

```
kubectl apply  -f - << END
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
  namespace: seldon
spec:
  name: car_predictor
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: gs://car_app_model/try1
        name: classifier
      name: default
      replicas: 1
END
```

The pod then gets the following status:
```
seldon          mlflow-default-0-classifier-6f4cc6994-gjn67                 0/2     Running            1          2m59s
```

Next I run 'kubectl describe pod mlflow-default-0-classifier-6f4cc6994-gjn67 -n seldon'  where I get the following events:
```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  50s               default-scheduler  Successfully assigned seldon/mlflow-default-0-classifier-6f4cc6994-gjn67 to gke-cluster-1-default-pool-27b34b9a-dbqf
  Normal   Pulled     49s               kubelet            Container image "gcr.io/kfserving/storage-initializer:v0.4.0" already present on machine
  Normal   Created    49s               kubelet            Created container classifier-model-initializer
  Normal   Started    49s               kubelet            Started container classifier-model-initializer
  Normal   Pulled     38s               kubelet            Container image "seldonio/mlflowserver:1.7.0" already present on machine
  Normal   Created    38s               kubelet            Created container classifier
  Normal   Started    38s               kubelet            Started container classifier
  Normal   Pulled     38s               kubelet            Container image "docker.io/seldonio/seldon-core-executor:1.7.0" already present on machine
  Normal   Created    38s               kubelet            Created container seldon-container-engine
  Normal   Started    38s               kubelet            Started container seldon-container-engine
  Warning  Unhealthy  5s (x3 over 15s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503
  Warning  Unhealthy  3s (x4 over 18s)  kubelet            Readiness probe failed: dial tcp 10.4.1.19:9000: connect: connection refused
```

After googling a bit I tried adding  readinessProbe field to the deployment file like this(note that I had to use validate = false):
```
kubectl apply --validate=false -f - << END
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
  namespace: seldon
spec:
  name: car_predictor
  livenessProbe:
    initialDelaySeconds: 100
  readinessProbe:
    initialDelaySeconds: 100

  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: gs://car_app_model/try1
        name: classifier
      name: default
      replicas: 1
END


```

Even after trying this the same error persists. What could be the problem?

**Comment by cliveseldon** [comment] 2021-05-17 09:33
Do you see any errors in the container logs?

**Comment by FilipVel** [comment] 2021-05-18 12:36
The seldon-container-engine is showing this error:
```
{"level":"error","ts":1621340845.169119,"logger":"SeldonRestApi","msg":"Ready check failed","error":"dial tcp 127.0.0.1:9000: connect: connection refused","stacktrace":"github.com/seldonio/seldon-core/executor/api/rest.(*SeldonRestApi).checkReady\n\t/workspace/api/rest/server.go:188\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.handleCORSRequests.func1\n\t/workspace/api/rest/middlewares.go:64\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/gorilla/mux.CORSMethodMiddleware.func1.1\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/middleware.go:51\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.xssMiddleware.func1\n\t/workspace/api/rest/middlewares.go:87\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.(*CloudeventHeaderMiddleware).Middleware.func1\n\t/workspace/api/rest/middlewares.go:47\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.puidHeader.func1\n\t/workspace/api/rest/middlewares.go:79\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2831\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1919"}
```

**Comment by Sheldelraze** [comment] 2021-05-22 05:11
Did you tried disabling istio sidecar like [this](https://github.com/SeldonIO/seldon-core/issues/3129#issuecomment-823168449)? I got this liveness probing problem too although it's 403 not 503

**Comment by sleebapaul** [comment] 2021-11-08 16:38
@axsaucedo Following up on the issue, any updates? I'm using Python 3.9. Is that a problem?

**Comment by sleebapaul** [comment] 2021-11-12 18:44
@axsaucedo @agrski The issue was caused by the Python version as I suspected. So I downgraded to Python 3.7.2. 

Now I've the following issue. The process stops while copying the model. It's been a while since I've been trying to deploy a simple model using `MLFLOWSERVER` with Seldon. Please let me know what is the working combination of versions of Python, Seldon and `MLFLOWSERVER` to complete the task. 


![Screenshot 2021-11-13 at 12 08 10 AM](https://user-images.githubusercontent.com/11848469/141518511-040d875c-79c2-495b-8089-02ee9d08a621.png)

**Comment by axsaucedo** [comment] 2021-12-06 09:53
Perfect - closing given that this has been answered, please reopen if still issue

**Closed by axsaucedo** 2021-12-06 09:53 UTC
Labels: bug
