### ISSUE TITLE
V2:  All model requests fail if the expected count of model replicas exceeds the count of server replicas

### ISSUE THREAD

**Issue by lynnmatrix** [SeldonIO/seldon-core#5124] opened 2023-09-05 07:59 UTC
## Describe the bug
All model requests fail if the expected count of model replicas exceeds the count of server replicas

## To reproduce
1.  set the count of server(triton) replicas to 1
2. set the count of any model(M) replicas to 2
3. send requests to model M in concurrency

## Expected behaviour
At least half of the requests succeed

## Environment

Seldon core v2.6.0

**Comment by agrski** [comment] 2023-09-05 09:26
Hi @lynnmatrix,

Is this if when you try to schedule a **new** model and send it requests, or when an **existing** model loses some amount of availability?

**Comment by lynnmatrix** [comment] 2023-09-05 09:34
@agrski  It is the first case that adding more replicas for existing model

**Comment by agrski** [comment] 2023-09-05 14:48
If this is a completely new model, it's likely that it simply isn't scheduling.

In any case, could you please check the `Model` resource, assuming you're running in Kubernetes, and post the status field, e.g. available via:
```bash
kubectl -n <namespace> get model <model name> -o jsonpath '{.status}' | jq
```

**Comment by lynnmatrix** [comment] 2023-09-06 02:16
@agrski  It goes like this. The triton replicas=1, and the model M replicas=1, now all requests for model M work well. 
Next, change the model M replicas to 2 (triggered by manual or auto scaling), keep the count of triton replicas=1, the model M status becomes unready, and all requests to model M fail.

`kubectl -n <namespace> get model <model name> -o jsonpath '{.status}' | jq` 
```json
{
  "conditions": [
    {
      "lastTransitionTime": "2023-09-06T02:07:09Z",
      "message": "ScheduleFailed",
      "reason": "****",
      "status": "False",
      "type": "ModelReady"
    },
    {
      "lastTransitionTime": "2023-09-06T02:07:09Z",
      "message": "ScheduleFailed",
      "reason": "****",
      "status": "False",
      "type": "Ready"
    }
  ],
  "replicas": 2
}
```

**Comment by agrski** [comment] 2023-09-06 15:35
Thanks for providing the extra details @lynnmatrix.  It looks like the scheduler is attempting to fully reschedule the model and removing its existing assignment(s).  This might be just the routing being affected and the model remaining loaded on the one Triton server, or it might be unloading that as well.

I believe the desired behaviour should be for existing assignments to remain and for the model to be considered partially available.

**Comment by lynnmatrix** [comment] 2023-09-07 02:40
I looked at the code. After model schedule fails (because there is no server replicas to arrange a new model replica), model.server will be reset to empty. Envoy try to remove and re-add the model's route, but fails to re-add because model.server is empty.

**Comment by cliveseldon** [comment] 2023-09-07 06:33
@sakoush This sounds like a regression bug from the reset server "fix" for other reasons?

**Comment by sakoush** [comment] 2023-09-07 10:30
there was a regression and it is fixed in https://github.com/SeldonIO/seldon-core/pull/5074  
@lynnmatrix could you try using `master`? we also have a rc with this fix that it likely to go you in the next week or so.

**Comment by lynnmatrix** [comment] 2023-09-07 10:44
Thanks. #5074 can fix this issue

**Comment by sakoush** [comment] 2023-10-09 11:41
@lynnmatrix I will close this issue as it seems it is fixed in your case now.

**Closed by sakoush** 2023-10-09 11:41 UTC
Labels: bug, v2
