### ISSUE TITLE
invalid jeager installation links in tracing notebook

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/seldon-core#4116] opened 2022-05-24 10:31 UTC
## Describe the bug
Links for Jeager installation in the notebook [Distributed Tracing Template
](https://github.com/SeldonIO/seldon-core/blob/master/examples/models/tracing/tracing.ipynb) seems to be invalid
```
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml 

error: unable to read URL "https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml", server reported 404 Not Found, status code=404
```

**Comment by RafalSkolasinski** [comment] 2022-05-25 08:50
Yes, we encountered this recently and will have to update the documentation. For now we pinned the jaeger chart https://github.com/SeldonIO/seldon-core/pull/4064 to earlier version but we will need to get it up to date.

**Comment by cliveseldon** [comment] 2022-06-24 06:03
Closing as fixed

**Closed as completed by cliveseldon** 2022-06-24 06:03 UTC
Labels: bug

**Comment by RafalSkolasinski** [comment] 2022-06-24 08:25
@cliveseldon I actually only fixed tests, so if the issue is about notebook it still needs to be fixed
